apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: al-umana
  labels:
    app: frontend
    app.kubernetes.io/part-of: al-umana
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
