apiVersion: v1
kind: Service
metadata:
  name: wa-gateway-service
  namespace: al-umana
  labels:
    app: wa-gateway
    app.kubernetes.io/part-of: al-umana
spec:
  type: ClusterIP
  selector:
    app: wa-gateway
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
